# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - node/install:
                node-version: '16.13'
            - run: node --version
  publish_release:
    executor: node/default
    steps:
      - checkout
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - node/install-packages:
                pkg-manager: npm
            - run: echo $CI_GITHUB_USER_NAME
            - run: echo $CI_GITHUB_USER_EMAIL
            - run: git config --global user.email $CI_GITHUB_USER_EMAIL
            - run: git config --global user.name $CI_GITHUB_USER_NAME
            - run: git log --pretty=oneline -n 1
            - run:
                name: ABC
                command:
                  STR='GNU/Linux is an operating system'
                  SUB='Linux'
                  if [[ "$STR" == *"$SUB"* ]]; then echo "It's there." fi
            - run:
                command: npm run release
                name: Create release
            - add_ssh_keys:
                fingerprints:
                  - ""
            - run: git push --follow-tags origin << pipeline.git.branch >>
            - persist_to_workspace:
                root: ~/project
                paths:
                  - .

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install-node-example
      - publish_release
