# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  
variables:
  CI_NAME: "digitalya-eusebiugagea"
  CI_EMAIL: "eusebiu.gagea@digitalya.co"

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
  publish_release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - echo $CI_USER
      - echo $CI_NAME
      - git config --global user.email $CI_EMAIL
      - git config --global user.name $CI_NAME
      - run:
          command: npm run release
          name: Create release
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install-node-example
      - publish_release
